export const vars = {
  surfaceBase: 'var(--surface-base)',
  surfaceRaised: 'var(--surface-raised)',
  surfaceOverlay: 'var(--surface-overlay)',
  surfaceSunken: 'var(--surface-sunken)',
  surfaceHover: 'var(--surface-hover)',
  surfaceSelected: 'var(--surface-selected)',
  contentPrimary: 'var(--content-primary)',
  contentSecondary: 'var(--content-secondary)',
  contentTertiary: 'var(--content-tertiary)',
  contentInverse: 'var(--content-inverse)',
  borderSubtle: 'var(--border-subtle)',
  borderStrong: 'var(--border-strong)',
  focusRing: 'var(--focus-ring)',
  accent: 'var(--color-accent)',
  accentHover: 'var(--color-accent-hover)',
  accentMuted: 'var(--color-accent-muted)',
  intentRead: 'var(--intent-read)',
  intentWrite: 'var(--intent-write)',
  intentRefactor: 'var(--intent-refactor)',
  intentDelete: 'var(--intent-delete)',
  changeAdded: 'var(--change-added)',
  changeModified: 'var(--change-modified)',
  changeBreaking: 'var(--change-breaking)',
  changeRenamed: 'var(--change-renamed)',
  statusActive: 'var(--status-active)',
  statusIdle: 'var(--status-idle)',
  statusWaiting: 'var(--status-waiting)',
  statusDone: 'var(--status-done)',
  statusDisconnected: 'var(--status-disconnected)',
  danger: 'var(--sev-danger)',
  warning: 'var(--sev-warning)',
  success: 'var(--sev-success)',
  info: 'var(--sev-info)',
  shadowOverlay: 'var(--shadow-overlay)',
  sans: 'var(--font-sans)',
  mono: 'var(--font-mono)',
} as const;

export const radius = {
  sm: 4,
  md: 6,
  lg: 8,
} as const;
